In [1]:
import torch 
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms

- code reference: https://github.com/yunjey/pytorch-tutorial/blob/master/tutorials/01-basics/pytorch_basics/main.py

### 1. Basic autograd example 1

In [2]:
# Create tensors.
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

# Build a computational graph.
y = w * x + b    # y = 2 * x + 3

# Compute gradients.
y.backward()

# Print out the gradients.
print(x.grad)    # x.grad = 2 
print(w.grad)    # w.grad = 1 
print(b.grad)    # b.grad = 1 

tensor(2.)
tensor(1.)
tensor(1.)


In [3]:
y

tensor(5., grad_fn=<AddBackward0>)

### 2. Basic autograd example 2

In [4]:
# Create tensors of shape (10, 3) and (10, 2).
x = torch.randn(10, 3)
y = torch.randn(10, 2)

In [5]:
x

tensor([[-1.2718, -0.4744, -0.0125],
        [-0.3706, -2.4003,  0.9577],
        [ 0.3875, -0.2880, -0.2223],
        [-0.4359,  0.0641, -1.5445],
        [-0.2237, -0.1857, -1.6613],
        [-0.5970, -0.1011, -0.4714],
        [-0.8319,  1.1907, -0.2570],
        [ 0.4690,  0.5261,  0.2640],
        [ 0.9082,  0.1295,  1.2311],
        [-0.0798, -1.3940,  0.8526]])

In [6]:
y

tensor([[ 1.5124,  1.4974],
        [ 1.3510, -0.1411],
        [ 0.0650,  0.1443],
        [ 1.0541,  0.2112],
        [ 0.1632,  0.2620],
        [ 0.0453,  0.1929],
        [ 1.4511,  0.1463],
        [-0.7161,  1.3905],
        [ 0.6964,  0.8098],
        [ 0.4797,  1.2248]])

In [7]:
# Build a fully connected layer.
linear = nn.Linear(3, 2)
print ('w: ', linear.weight)
print()
print ('b: ', linear.bias)

w:  Parameter containing:
tensor([[-0.4909, -0.3144,  0.0056],
        [-0.2543,  0.3284,  0.2732]], requires_grad=True)

b:  Parameter containing:
tensor([-0.1618,  0.3372], requires_grad=True)


In [8]:
# Build loss function and optimizer.
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

In [9]:
criterion

MSELoss()

In [10]:
optimizer

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [11]:
# Forward pass.
pred = linear(x)
pred

tensor([[ 0.6116,  0.5013],
        [ 0.7801, -0.0952],
        [-0.2627,  0.0833],
        [ 0.0233,  0.0470],
        [-0.0030, -0.1209],
        [ 0.1604,  0.3269],
        [-0.1292,  0.8695],
        [-0.5559,  0.4628],
        [-0.6414,  0.4852],
        [ 0.3204,  0.1326]], grad_fn=<AddmmBackward0>)

In [12]:
# Compute loss.
loss = criterion(pred, y)
print('loss: ', loss.item())

loss:  0.5278869867324829


In [13]:
# You can also perform gradient descent at the low level.
# linear.weight.data.sub_(0.01 * linear.weight.grad.data)
# linear.bias.data.sub_(0.01 * linear.bias.grad.data)

# Print out the loss after 1-step gradient descent.
pred = linear(x)
loss = criterion(pred, y)
print('loss after 1 step optimization: ', loss.item())

loss after 1 step optimization:  0.5278869867324829


###  3. Loading data from numpy

In [14]:
# Create a numpy array.
x = np.array([[1, 2], [3, 4]])

# Convert the numpy array to a torch tensor.
y = torch.from_numpy(x)

# Convert the torch tensor to a numpy array.
z = y.numpy()

print(f"type of x:{type(x)},\nx:\n{x}")
print(f"\ntype of x:{type(y)},\ny:\n{y}")
print(f"\ntype of z:{type(z)},\nz:\n{z}")

type of x:<class 'numpy.ndarray'>,
x:
[[1 2]
 [3 4]]

type of x:<class 'torch.Tensor'>,
y:
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

type of z:<class 'numpy.ndarray'>,
z:
[[1 2]
 [3 4]]


### 4. Pretrained model  

In [15]:
# Download and load the pretrained ResNet-18.
resnet = torchvision.models.resnet18(pretrained=True)

c:\python3_7\lib\site-packages\torchvision\models\_utils.py:209: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  f"The parameter '{pretrained_param}' is deprecated since 0.13 and may be removed in the future, "
c:\python3_7\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


In [16]:
resnet

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  

In [17]:
# If you want to finetune only the top layer of the model, set as below.
for param in resnet.parameters():
    param.requires_grad = False

In [18]:
# Replace the top layer for finetuning.
resnet.fc = nn.Linear(resnet.fc.in_features, 100)  # 100 is an example.

In [19]:
# Forward pass.
images = torch.randn(64, 3, 224, 224)
outputs = resnet(images)
print (outputs.size())     # (64, 100)

torch.Size([64, 100])


### 5. Save and load the model      

In [21]:
# Save and load the entire model.
torch.save(resnet, '../result/testing_model_from_basics_notebook.ckpt')
model = torch.load('../result/testing_model_from_basics_notebook.ckpt')

In [20]:
# Save and load only the model parameters (recommended).
torch.save(resnet.state_dict(), '../result/params_from_basics_notebook.ckpt')
resnet.load_state_dict(torch.load('../result/params_from_basics_notebook.ckpt'))

<All keys matched successfully>